FROM node:22-alpine3.20

RUN addgroup -S frontend 
RUN adduser -S frontend -G frontend

WORKDIR /app
# COPY . . 
RUN chown -R frontend:frontend /app

USER frontend
EXPOSE 3000
CMD ["sh", "-c","npm run build && npm start"]