services:
  frontend:
    build:
      context: ./frontend  # Set the context to the frontend directory
      dockerfile: Dockerfile.production  # Specify the Dockerfile in the frontend directory  # Expose port 3000 to access the Next.js app
    volumes:
      - ./frontend:/app  # Mount the frontend directory to /app in the container
    environment:
      - NODE_ENV=production  # Set environment variable for development
    networks:
      - app-network

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile.production
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  database: 
    image: mongo:latest
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx  # Build the nginx Dockerfile
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
