services:
  frontend:
    build:
      context: ./frontend  # Set the context to the frontend directory
      dockerfile: Dockerfile.development # Specify the Dockerfile in the frontend directory
    ports:
      - "3000:3000"  # Expose port 3000 to access the Next.js app
    volumes:
      - ./frontend:/app  # Mount the frontend directory to /app in the container
    environment:
      - NODE_ENV=development  # Set environment variable for development
      
  
  
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile.development
    ports: 
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  database: 
    image: mongo:latest
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"
